version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    open-pull-requests-limit: 3
    schedule:
      interval: daily
      time: "01:00"
      timezone: "Asia/Shanghai"
    labels:
      - "area/dependency"
      - "release-note-none"
      - "ok-to-test"
      - "kind/cleanup"
      - "lgtm"
      - "approved"
  - package-ecosystem: "gomod"
    directory: "/kubetest2-aks/"
    open-pull-requests-limit: 3
    schedule:
      interval: daily
      time: "01:00"
      timezone: "Asia/Shanghai"
    labels:
      - "area/dependency"
      - "release-note-none"
      - "ok-to-test"
      - "kind/testing"
      - "lgtm"
      - "approved"
  - package-ecosystem: "gomod"
    directory: "/pkg/azureclients/v2/"
    schedule:
      interval: daily
      time: "01:00"
      timezone: "Asia/Shanghai"
    labels:
      - "area/dependency"
      - "release-note-none"
      - "ok-to-test"
      - "kind/testing"
      - "lgtm"
      - "approved"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      time: "01:00"
      timezone: "Asia/Shanghai"
    labels:
      - "area/dependency"
      - "release-note-none"
      - "ok-to-test"
      - "kind/cleanup"
      - "lgtm"
      - "approved"
      
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
      time: "01:00"
      timezone: "Asia/Shanghai"
    labels:
      - "area/dependency"
      - "release-note-none"
      - "ok-to-test"
      - "kind/testing"
      - "lgtm"
      - "approved"
      
  - package-ecosystem: "npm"
    directory: "/site/"
    schedule:
      interval: daily
      time: "01:00"
      timezone: "Asia/Shanghai"
    labels:
      - "area/dependency"
      - "release-note-none"
      - "ok-to-test"
      - "kind/documentation"
      - "lgtm"
      - "approved"
      
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: daily
      time: "01:00"
      timezone: "Asia/Shanghai"
    open-pull-requests-limit: 3
    labels:
      - "area/dependency"
      - "release-note-none"
      - "ok-to-test"
      - "kind/cleanup"
      - "lgtm"
      - "approved"
    target-branch: "release-1.24"
    ignore:
      - dependency-name: "k8s.io/*"
        versions: [">=0.25.0"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
      time: "01:00"
      timezone: "Asia/Shanghai"
    target-branch: "release-1.24"
    labels:
      - "area/dependency"
      - "release-note-none"
      - "ok-to-test"
      - "kind/testing"
      - "lgtm"
      - "approved"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      time: "01:00"
      timezone: "Asia/Shanghai"
    target-branch: "release-1.24"
    labels:
      - "area/dependency"
      - "release-note-none"
      - "ok-to-test"
      - "kind/cleanup"
      - "lgtm"
      - "approved"
  - package-ecosystem: "gomod"
    directory: "/"
    open-pull-requests-limit: 3
    schedule:
      interval: daily
      time: "01:00"
      timezone: "Asia/Shanghai"
    labels:
      - "area/dependency"
      - "release-note-none"
      - "ok-to-test"
      - "kind/cleanup"
      - "lgtm"
      - "approved"
    target-branch: "release-1.23"
    ignore:
      - dependency-name: "k8s.io/*"
        versions: [">=0.24.0"]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
      time: "01:00"
      timezone: "Asia/Shanghai"
    target-branch: "release-1.23"
    labels:
      - "area/dependency"
      - "release-note-none"
      - "ok-to-test"
      - "kind/testing"
      - "lgtm"
      - "approved"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      time: "01:00"
      timezone: "Asia/Shanghai"
    target-branch: "release-1.23"
    labels:
      - "area/dependency"
      - "release-note-none"
      - "ok-to-test"
      - "kind/cleanup"
      - "lgtm"
      - "approved"
  - package-ecosystem: "gomod"
    directory: "/"
    open-pull-requests-limit: 3
    schedule:
      interval: daily
      time: "01:00"
      timezone: "Asia/Shanghai"
    labels:
      - "area/dependency"
      - "release-note-none"
      - "ok-to-test"
      - "kind/cleanup"
      - "lgtm"
      - "approved"
    target-branch: "release-1.25"
    ignore:
      - dependency-name: "k8s.io/*"
        versions: [">=0.26.0"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
      time: "01:00"
      timezone: "Asia/Shanghai"
    target-branch: "release-1.25"
    labels:
      - "area/dependency"
      - "release-note-none"
      - "ok-to-test"
      - "kind/testing"
      - "lgtm"
      - "approved"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      time: "01:00"
      timezone: "Asia/Shanghai"
    target-branch: "release-1.25"
    labels:
      - "area/dependency"
      - "release-note-none"
      - "ok-to-test"
      - "kind/cleanup"
      - "lgtm"
      - "approved"
  - package-ecosystem: "gomod"
    directory: "/"
    open-pull-requests-limit: 3
    schedule:
      interval: daily
      time: "01:00"
      timezone: "Asia/Shanghai"
    labels:
      - "area/dependency"
      - "release-note-none"
      - "ok-to-test"
      - "kind/cleanup"
      - "lgtm"
      - "approved"
    target-branch: "release-1.26"
    ignore:
      - dependency-name: "k8s.io/*"
        versions: [">=0.27.0"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
      time: "01:00"
      timezone: "Asia/Shanghai"
    target-branch: "release-1.26"
    labels:
      - "area/dependency"
      - "release-note-none"
      - "ok-to-test"
      - "kind/testing"
      - "lgtm"
      - "approved"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      time: "01:00"
      timezone: "Asia/Shanghai"
    target-branch: "release-1.26"
    labels:
      - "area/dependency"
      - "release-note-none"
      - "ok-to-test"
      - "kind/cleanup"
      - "lgtm"
      - "approved"

